In [1]:
import numpy as np
import pandas as pd

In [2]:
falsy_values = (0, False, None, '', [], {})

In [3]:
any(falsy_values)

False

Numpy has a special "nullable" value for numbers which is np.nan. It's NaN: "Not a number"

In [4]:
np.nan

nan

In [5]:
3 + np.nan

nan

In [6]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [7]:
a.sum()


nan

In [8]:
a.mean()

nan

This is better than regular None values, which in the previous examples would have raised an exception:



In [9]:
3 + None

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [10]:
a = np.array([1, 2, 3, np.nan, None, 4], dtype='float')

In [11]:
a

array([ 1.,  2.,  3., nan, nan,  4.])

Numpy also supports an "Infinite" type:

In [13]:
np.inf

inf

In [14]:
3 + np.inf

inf

In [30]:
b = np.array([1, 2, 3, np.inf, np.nan,  4], dtype=np.float64)

In [31]:
b.sum()

nan

Checking for nan or inf

here are two functions: np.isnan and np.isinf that will perform the desired checks:

In [32]:
np.isnan(np.nan)

True

In [33]:
np.isinf(np.inf)

True

In [34]:
b

array([ 1.,  2.,  3., inf, nan,  4.])

In [35]:
np.isinf(b)

array([False, False, False,  True, False, False])

In [36]:
set = np.isinf(b)
set

array([False, False, False,  True, False, False])

 And the joint operation can be performed with np.isfinite.

In [37]:
b

array([ 1.,  2.,  3., inf, nan,  4.])

In [38]:
np.isfinite(b)

array([ True,  True,  True, False, False,  True])

In [39]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [40]:
a[np.isfinite(a)]

array([1., 2., 3., 4.])

In [41]:
a[np.isfinite(a)].sum()

10.0

In [42]:
a[np.isfinite(a)].mean()


2.5