In [6]:
!pip install numpy


  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/72/b2/02770e60c4e2f7e158d923ab0dea4e9f146a2dbf267fec6d8dc61d475689/numpy-1.25.2-cp311-cp311-win_amd64.whl.metadata
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.5 MB 311.2 kB/s eta 0:00:50
   ---------------------------------------- 0.1/15.5 MB 387.0 kB/s eta 0:00:40
   ---------------------------------------- 0.2/15.5 MB 366.6 kB/s eta 0:00:4

In [7]:
import sys
import numpy as np

In [8]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [11]:
a = np.array([1,2,3,4])

In [12]:
b = np.array([0, 0.5, 2.5, 3.5,4.5])

In [13]:
a[0], a[1]

(1, 2)

In [14]:
a[0:]

array([1, 2, 3, 4])

In [15]:
a[1:3]

array([2, 3])

In [16]:
a[1:-1]

array([2, 3])

In [17]:
a[::2]

array([1, 3])

In [18]:
b[0], b[2], b[-1]

(0.0, 2.5, 4.5)

In [19]:
a[[0,1]]

array([1, 2])

In [20]:
a

array([1, 2, 3, 4])

In [21]:
a.dtype

dtype('int32')

In [22]:
b

array([0. , 0.5, 2.5, 3.5, 4.5])

In [23]:
b.dtype

dtype('float64')

In [25]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [28]:
np.array([0.5,1.5, 3.5, 4.9], dtype=np.int8)

array([0, 1, 3, 4], dtype=int8)

In [29]:
c = np.array(['a', 'b', 'c'])

In [30]:
c.dtype

dtype('<U1')

In [31]:
d = np.array([{'a': 1}, sys])

In [32]:
d.dtype

dtype('O')

In [33]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [34]:
A.shape

(2, 3)

In [35]:
A.ndim

2

In [36]:
A.size

6

In [37]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [38]:
A[1]

array([4, 5, 6])

In [39]:
A[1][0]

4

In [40]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
A[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [42]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [43]:

A[:2, 2:]

array([[3],
       [6]])

In [44]:
A


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
A[1] = np.array([10,20,30])

In [47]:
A


array([[ 1,  2,  3],
       [10, 20, 30],
       [ 7,  8,  9]])

In [48]:
A[2]= 99

In [49]:
A

array([[ 1,  2,  3],
       [10, 20, 30],
       [99, 99, 99]])

In [50]:
c = np.array([20,30,40,50])

In [51]:
C

NameError: name 'C' is not defined

In [52]:
c

array([20, 30, 40, 50])

In [53]:
a.sum()

10

In [54]:
c.sum()

140

In [55]:
c.mean()


35.0

In [56]:
c.std()

11.180339887498949

In [57]:
c.var()

125.0

In [58]:
d= np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [59]:
d.sum(axis=0)

array([12, 15, 18])

In [60]:
A.sum(axis=1)

array([  6,  60, 297])

In [62]:
a = np.arange(7)


In [63]:
a

array([0, 1, 2, 3, 4, 5, 6])

In [64]:
a +=10

In [65]:
a

array([10, 11, 12, 13, 14, 15, 16])

In [66]:
a + 10

array([20, 21, 22, 23, 24, 25, 26])

In [67]:
a

array([10, 11, 12, 13, 14, 15, 16])

In [68]:
l = [0, 1, 2, 3]

In [69]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [70]:
e = np.arange(4)

In [71]:
e

array([0, 1, 2, 3])

In [74]:
e[0], e[-1]


(0, 3)

In [75]:
e[[True, False, False, True]]

array([0, 3])

In [77]:
e[[True, False, True, False]]

array([0, 2])

In [78]:
e >= 2

array([False, False,  True,  True])

In [80]:
e[e >= 2]

array([2, 3])

In [81]:
e.mean()

1.5

In [84]:
e[e > e.mean()]

array([2, 3])

In [85]:
e[~(e > e.mean())]

array([0, 1])

In [86]:
e[(e == 0) | (e == 1)]

array([0, 1])

In [91]:
A = np.random.randint(100, size=(3, 3))

In [92]:
A

array([[74,  0, 56],
       [ 9, 80, 67],
       [47, 61, 56]])

In [93]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([74, 56, 80, 47, 56])

In [94]:
A > 30

array([[ True, False,  True],
       [False,  True,  True],
       [ True,  True,  True]])

In [95]:
A[A > 30]

array([74, 56, 80, 67, 47, 61, 56])

In [96]:
F = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [97]:
G = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [98]:
A.dot(B)

NameError: name 'B' is not defined

In [99]:
F.dot(G)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [100]:
A @ B

NameError: name 'B' is not defined

In [101]:
F @ G

array([[20, 14],
       [56, 41],
       [92, 68]])

In [102]:
B.T


NameError: name 'B' is not defined

In [103]:
G.T

array([[6, 4, 2],
       [5, 3, 1]])

In [104]:
G.T @ F

array([[36, 48, 60],
       [24, 33, 42]])

In [105]:
sys.getsizeof(1)

28

In [106]:
np.random.random(size=2)

array([0.53506782, 0.99262373])

In [107]:
np.random.normal(size=2)

array([0.07582234, 0.85312576])

In [108]:
np.random.rand(size =2)

TypeError: rand() got an unexpected keyword argument 'size'

In [109]:
np.random.randint(size =2)

TypeError: randint() takes at least 1 positional argument (0 given)

In [110]:
np.random.rand(2, 4)

array([[0.50023927, 0.94399505, 0.76471371, 0.59865387],
       [0.22159899, 0.38300972, 0.14498725, 0.14886471]])

In [111]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [113]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [114]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [115]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [116]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [117]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [118]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [119]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [120]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [121]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [122]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [123]:
np.empty((2, 2))


array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [124]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [125]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [126]:
"Hello World"[6]

'W'